[package]
name = "chip_8"
version = "0.8.0"
authors = ["Herculean <55994229+Herkulisch@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
crossterm = "0.20"
